networks:
  MengGoods:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    container_name: mysql-1
    ports:
      - "3306:3306"
    environment:
      - TZ=${TZ}
      - MYSQL_PASSWORD=123456        
      - MYSQL_ROOT_PASSWORD=123456   
      - MYSQL_ALLOW_EMPTY_PASSWORD:"no"
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - MengGoods

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    container_name: redis-1
    command: redis-server --loadmodule /opt/redis-stack/lib/redisbloom.so --requirepass 123456
    restart: always
    volumes:
      - ./data/redis:/data
    networks:
      - MengGoods

  etcd:
    image: rancher/coreos-etcd:v3.4.16-rancher1
    container_name: etcd-1
    restart: always
    environment:
      - TZ=${TZ}
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-1:2379
    ports:
      - "2379:2379"
    volumes:
      - ./data/etcd:/data  
    networks:
      - MengGoods
  
  jaeger:
    container_name: jaeger-1
    restart: always
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
    networks:
      - MengGoods
  elasticsearch:
    image: elasticsearch:8.17.0
    container_name: elasticsearch-1
    user: elasticsearch
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - MengGoods
  
  
  kibana:
    image: kibana:8.17.0
    container_name: kibana-1
    user: root
    command: ["kibana", "--allow-root"]
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch-1:9200"]
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    volumes:
      - ./data/kibana:/usr/share/kibana/data
    restart: always
    networks:
      - MengGoods
    
  filebeat:
    image: elastic/filebeat:8.17.0
    container_name: filebeat-1
    user: root
    command: filebeat -e -E "strict.perms=false"
    volumes:
      - ./config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml # 挂载配置文件
      - ./data/filebeat:/usr/share/filebeat/data  # 持久化注册表文件
      - ./logs:/usr/share/filebeat/logs  # 挂载日志目录
    depends_on:
      - elasticsearch
    restart: always
    networks:
      - MengGoods
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-1
    hostname: prometheus
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - otelCollector
    networks:
      - MengGoods

  otelCollector:
      image: otel/opentelemetry-collector-contrib:latest
      container_name: collector-1
      command: [ "--config=/etc/otel-collector-config.yaml" ]
      volumes:
      - ./config/opentelemetry/otelCollector.yaml:/etc/otel-collector-config.yaml:rw
      ports:
      - "4317:4317"  
      - "4318:4318"  
      - "55679:55679"
      - "8888:8888"  
      - "8889:8889"  
      - "13133:13133"
      depends_on:
       - jaeger
      networks:
       - MengGoods

  grafana:
      image: grafana/grafana:latest
      container_name: grafana-1
      ports:
      - "3000:3000"
      depends_on:
      - prometheus
      networks:
      - MengGoods

  kafka:
    container_name: kafka-1
    image: apache/kafka:3.7.0
    restart: always
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      # KRaft 模式必须参数
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      
      # 监听器配置 (支持宿主机 9094 访问)
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092,EXTERNAL://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE:"true"
      
      # 单机模式副本设置
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
    volumes:
      - ./data/kafka:/var/lib/kafka/data
    networks:
      - MengGoods

  kafka-ui:
    container_name: kafka-ui-1
    image: provectuslabs/kafka-ui:latest
    restart: always
    depends_on:
      - kafka
    ports:
      - "9091:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:9092
    networks:
      - MengGoods
  
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq-1
    hostname: rabbitmq-server
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
      
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
      
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    networks:
      - MengGoods